USE [master]
GO

/****** Object:  Database [desafiodev]    Script Date: 04/07/2024 18:49:49 ******/

CREATE DATABASE [desafiodev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'desafiodev', FILENAME = N'C:\Users\guira\desafiodev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'desafiodev_log', FILENAME = N'C:\Users\guira\desafiodev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [desafiodev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [desafiodev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [desafiodev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [desafiodev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [desafiodev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [desafiodev] SET ARITHABORT OFF 
GO

ALTER DATABASE [desafiodev] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [desafiodev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [desafiodev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [desafiodev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [desafiodev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [desafiodev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [desafiodev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [desafiodev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [desafiodev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [desafiodev] SET  ENABLE_BROKER 
GO

ALTER DATABASE [desafiodev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [desafiodev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [desafiodev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [desafiodev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [desafiodev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [desafiodev] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [desafiodev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [desafiodev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [desafiodev] SET  MULTI_USER 
GO

ALTER DATABASE [desafiodev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [desafiodev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [desafiodev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [desafiodev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [desafiodev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [desafiodev] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [desafiodev] SET QUERY_STORE = OFF
GO

ALTER DATABASE [desafiodev] SET  READ_WRITE 
GO

